### ISSUE TITLE
A Conversation should have many Comments

### ISSUE THREAD

**Issue by mdarby** [columbusrb/conclave#2]

**Comment by skord** [comment]
I'm interesting in knowing how people feel about this one. Is the conversation simply a mass of comments, and when creating a conversation you accept a comment as a nested attribute for the OP? Or because there might be different validations on the original post does the Conversation model fit something more akin to a blog post having many comments?

**Comment by mdarby** [comment]
My original vision on this would be inline with your first assumption -- Conversation is largely a container for a bunch of Comments sorted by date. The Conversation would really only have a :title. The validations would just ensure a :title is present. 

We should keep it simple until it can no longer be :)
