### ISSUE TITLE
Comment Markup: BBCode or Markdown

### ISSUE THREAD

**Issue by DVG** [columbusrb/conclave#21]
Having previously started a forum project, this is something I never came to consensus with myself about.

BBCode is well adopted in the forum world and almost all forum-goers are familiar with it. However it has relatively poor support in the Ruby world for a drop-in parser, and will require significant work to build an implementation or extend an existing on beyond the standard tags.  Ruby BBCode (ruby-bbcode) was my personal preference for a parser so far, however it's last update was more than 8 months ago.

Markdown is extremely well supported in the Ruby world, Redcarpet (https://github.com/vmg/redcarpet) in particular will add it easily to the application, but outside the technical world not a lot of people are familiar with it.

**Comment by skord** [comment]
Thinking to other forums, BBCode is the defacto standard, but if I think about sites like Reddit & Github, it's pretty much markdown the whole way, so I don't think users will be too confused. Some sort of minimal JS helpers for bold, italics, etc might ease the barrier, plus since we're using bootstrap, there's plenty of neato icons and buttons for this sort of thing. 

I've used kramdown (http://kramdown.rubyforge.org/) in the past, and it's pretty darn fast and backwards compatible with markdown, that's my vote. 
- mike

**Comment by mdarby** [comment]
+1 Markdown

**Comment by vampirechicken** [comment]
On Fri, Sep 21, 2012 at 2:28 PM, Bradley Temple notifications@github.comwrote:

> Having previously started a forum project, this is something I never came
> to consensus with myself about.

Abstract it, build the one you like. Somebody will build the others as long
as the abstraction is in place. Then you get to let the user choose, at the
cost of a markup_type column.

Len.

## 

lenjaffe@lenjaffe.com   614-404-4214
Proprietor: http://www.theycomewithcheese.com/ - An Homage to Fromage
Grubmaster: Greenbar http://www.greenbartraining.org/ 2011, 2010, 2009,
Grub Asst. 2008, Trained 2007.

**Comment by adamalbrecht** [comment]
I prefer Markdown and don't think we need to cater to everyone's needs, but having said that @vampirechicken is probably right in that we could just abstract and (eventually) support both.
