### ISSUE TITLE
Rough-in Conversations#index

### ISSUE THREAD

**Issue by mdarby** [columbusrb/conclave#25]
In this template, we'll need a list of Conversations within a particular Forum. It should show each Conversations' title as a link to Conversations#show, last comment date, and the number of related Comments.

**Comment by gharraph** [comment]
I have couple questions about Active Admin! This is my first time to deal with this gem. I noticed that routes for Forums and Conversations are nested under admin! The question is; how regular user (not admin) can access Forums and Conversations to be able to comment? Should I add more route matchers to routes.rb to create routes for regular user ( ex: forums#show instead of  admin/forums#show)?

**Comment by mdarby** [comment]
Forum, Conversation, and Comment routes will be exposed via standard Rails MVC so that logged in users can use the site. ActiveAdmin areas are only for admins.
