### ISSUE TITLE
ConversationsController#create on blank form raises exception on save!

### ISSUE THREAD

**Issue by rjo1970** [columbusrb/conclave#63]
Looks like @conversation.save! raises an exception rather than returning false, which breaks when no title is entered.

I have a Cucumber scenario but changing the action to if @conversation.valid? && @conversation.save! seems very, very wrong to me.

**Comment by skord** [comment]
The controller appears a bit weird to me, trying to wrap my head around it. Since a Conversation accepts nested attributes for a comment, I'd figured the easier way to do this would be like this: 

https://github.com/plataformatec/simple_form/wiki/Nested-Models

I see there's the extra attributes we're setting on the comment, like the creator, but those might fly better with a params merge. The upside of using the method in the link is you won't have to explicitly build the relationships.

**Comment by skord** [comment]
I'm uncertain if I want to include this in master right away, but I've got two commits skord@e6111fe and skord@fc88dc4cc958a6bca9d299276bf3a1c4683419d5 which take a shot at this. Actually there's another one two because I happily command-Z'd before committing. 

First commit uses implicit methods for defining the association rather than explicitly doing so. Unfortunately there's a bit of a hack to get the comment user_id to match up. Other ways in my head of doing that can screw up mass assignment or cause a race condition in assigning the owner. Unfortunately, because of however activerecord assigns the parent model on the child, you can't assign the ID of the conversation to the comment, however this is handled implicitly in the controller. 

Side note, I'm guessing this is probably a better way of doing that should we ever have a permissions system for users on different forums. 

The second commit fixes some specs, removes them actually. I'd probably have to dig pretty deep into AR to know why this happens, but I'm guessing its some sort of validation/callback issue, I touched on it when discussing the first commit. 

Third commit skord@21dc2f0182e8350dd11d7992ec9f7e24ce627b98 changes save! to save, which raises the proper exception and re-renders the form with the proper error messages. I'd have done that first, but Command-Z happy.

**Comment by mdarby** [comment]
I think this is cleared up in 59dcb6356628c48acabed28a845ac78ef7b30419
