### ISSUE TITLE
Install ActiveAdmin for the admin area

### ISSUE THREAD

**Issue by mdarby** [columbusrb/conclave#8]
The default login is:
admin@example.com / password

**Comment by skord** [comment]
This can be closed by a07807f91d5bd4fe694c9e833982e2fc26a9e8cb.

Instead of using an AdminUser model separate from the User model, the User model was given roles. 

Suppose there should be a rake task or migration to add the example user, as admin@example.com currently doesn't exist and you'd have to irb it to create an admin user since the role attribute is protected. 

_hence me not actually closing this_

**Comment by mdarby** [comment]
Great idea. Would you mind creating the default admin/password account? I'll merge and close then. Thanks!
