### ISSUE TITLE
Updating account conflict when using OAuth-based User

### ISSUE THREAD

**Issue by mdarby** [columbusrb/conclave#83]
An OAuth-based User won't necessarily have an email, nor a password. We can figure out if the User is socially-created (`@user.provider.present?`), so maybe we hide the whole password deal on `/users/edit` if so?

**Comment by skord** [comment]
This is such a PITA, I gave up on twitter integration on my last project. What I ended up doing was auto-generating a password to meet validations and signing in the user bypassing it. The problem is that it's a real hack and it won't fly in rails 4. I added you as a collaborator on that private project which I intend on open sourcing later this week after I redact the passwords and whatnot, it may help with how to handle this. I'm knee deep in actual work which is killing me, otherwise I'd take advantage of the do-ocracy and just commit it mysel.

**Comment by pairing** [comment]
When a person logs in from Twitter the app now checks for an email -- if one doesn't exist it will present a form to add one.
